# Generated by Django 2.0.1 on 2018-01-24 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usuario_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='last_login',
        ),
    ]
