# Generated by Django 2.0.1 on 2018-01-28 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_usuario_last_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
