# Generated by Django 2.0.1 on 2018-02-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('idPartido', models.AutoField(primary_key=True, serialize=False)),
                ('equipo1', models.CharField(max_length=30)),
                ('equipo2', models.CharField(max_length=30)),
                ('monto1', models.FloatField()),
                ('monto2', models.FloatField()),
                ('montoempate', models.FloatField()),
                ('estado', models.BooleanField(default=True)),
                ('fecha', models.DateField()),
                ('Grupo', models.CharField(max_length=1)),
            ],
        ),
    ]
