# Generated by Django 2.0.1 on 2018-02-20 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polla', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apuestas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField()),
                ('ganancia', models.FloatField()),
                ('pronostico', models.CharField(max_length=1)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polla.Partido')),
            ],
        ),
    ]
