# Generated by Django 2.0.1 on 2018-01-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitacion',
            name='estado',
            field=models.CharField(default='pendiente', max_length=11),
        ),
        migrations.AlterField(
            model_name='invitacion',
            name='owner',
            field=models.CharField(max_length=30),
        ),
    ]
