# Generated by Django 2.0.1 on 2018-01-28 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0002_auto_20180128_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitacion',
            name='grupo',
        ),
    ]
