# Generated by Django 2.0.1 on 2018-02-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0004_invitacion_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitacion',
            name='invitado',
            field=models.CharField(max_length=30),
        ),
    ]
