# Generated by Django 2.0.1 on 2018-02-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaTrivia',
            fields=[
                ('idPregunta', models.AutoField(primary_key=True, serialize=False)),
                ('descPregunta', models.CharField(max_length=250)),
                ('respuesta', models.CharField(max_length=150)),
                ('incorrecta1', models.CharField(max_length=150)),
                ('incorrecta2', models.CharField(max_length=150)),
                ('incorrecta3', models.CharField(max_length=150)),
            ],
        ),
    ]
