# Generated by Django 2.0.1 on 2018-02-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaTrivia',
            fields=[
                ('idPregunta', models.AutoField(primary_key=True, serialize=False)),
                ('descPregunta', models.CharField(max_length=250)),
                ('respuesta', models.CharField(max_length=150)),
                ('incorrecta1', models.CharField(max_length=150)),
                ('incorrecta2', models.CharField(max_length=150)),
                ('incorrecta3', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='scoretrivia',
            fields=[
                ('idPregunta', models.AutoField(primary_key=True, serialize=False)),
                ('grupo', models.CharField(max_length=30)),
                ('user', models.CharField(max_length=20)),
                ('puntaje', models.CharField(max_length=2)),
                ('idpreguntaTrivia', models.CharField(max_length=10)),
            ],
        ),
    ]
