# Generated by Django 2.0.1 on 2018-02-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='scoretrivia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=30)),
                ('idPregunta', models.CharField(max_length=1000)),
                ('user', models.CharField(max_length=20)),
            ],
        ),
    ]
