# Generated by Django 2.0.1 on 2018-02-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0002_delete_scoretrivia'),
    ]

    operations = [
        migrations.CreateModel(
            name='scoretrivia',
            fields=[
                ('idPregunta', models.AutoField(primary_key=True, serialize=False)),
                ('grupo', models.CharField(max_length=30)),
                ('user', models.CharField(max_length=20)),
                ('puntaje', models.CharField(max_length=2)),
                ('idpreguntaTrivia', models.CharField(max_length=10)),
            ],
        ),
    ]
