# Generated by Django 2.0.1 on 2018-02-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0003_scoretrivia'),
    ]

    operations = [
        migrations.CreateModel(
            name='salatrivia',
            fields=[
                ('idjuego', models.AutoField(primary_key=True, serialize=False)),
                ('nombreJuego', models.CharField(max_length=30)),
                ('grupo', models.CharField(max_length=30)),
                ('cantpreguntas', models.IntegerField(max_length=2)),
                ('estado', models.CharField(max_length=11)),
            ],
        ),
    ]
