# Generated by Django 2.0.1 on 2018-02-11 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0005_auto_20180211_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='salatrivia',
            fields=[
                ('idjuego', models.AutoField(primary_key=True, serialize=False)),
                ('nombreJuego', models.CharField(max_length=30)),
                ('grupo', models.CharField(max_length=30)),
                ('cantpreguntas', models.IntegerField(max_length=2)),
                ('estado', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='scoretrivia',
            fields=[
                ('idtrivia', models.AutoField(primary_key=True, serialize=False)),
                ('grupo', models.CharField(max_length=30)),
                ('user', models.CharField(max_length=20)),
                ('puntaje', models.CharField(max_length=2)),
                ('idpreguntaTrivia', models.CharField(max_length=10)),
                ('idjueg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia.salatrivia')),
            ],
        ),
    ]
