# Generated by Django 2.0.1 on 2018-02-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0006_scoretrivia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoretrivia',
            name='id',
        ),
        migrations.AlterField(
            model_name='scoretrivia',
            name='idPregunta',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
