# Generated by Django 2.0.1 on 2018-02-12 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0007_auto_20180211_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoretrivia',
            name='idjueg',
        ),
        migrations.DeleteModel(
            name='salatrivia',
        ),
        migrations.DeleteModel(
            name='scoretrivia',
        ),
    ]
