# Generated by Django 2.0.1 on 2018-02-12 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0009_pagosala_salatrivia_scoretrivia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PagoSala',
        ),
    ]
