# Generated by Django 2.0.1 on 2018-02-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0010_delete_pagosala'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoSala',
            fields=[
                ('idjuego', models.AutoField(primary_key=True, serialize=False)),
                ('nombreJuego', models.CharField(max_length=30)),
                ('grupo', models.CharField(max_length=30)),
                ('user', models.CharField(max_length=20)),
                ('estadopago', models.CharField(max_length=10)),
            ],
        ),
    ]
