# Generated by Django 2.0.1 on 2018-02-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0012_ganadorpozo_salaapuestas_scorejuego'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorejuego',
            name='resultado',
            field=models.FloatField(default=0),
        ),
    ]
