# Generated by Django 2.0.1 on 2018-02-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipoideal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadorpais',
            name='nombre',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='jugadorpais',
            name='pais',
            field=models.CharField(max_length=70),
        ),
    ]
