# Generated by Django 2.0.1 on 2018-02-20 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipoideal', '0005_partido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partido',
        ),
    ]
