# Generated by Django 2.0.1 on 2018-02-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipoideal', '0006_delete_partido'),
    ]

    operations = [
        migrations.CreateModel(
            name='salatrivia',
            fields=[
                ('idjuego', models.AutoField(primary_key=True, serialize=False)),
                ('nombreJuego', models.CharField(max_length=30)),
                ('grupo', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=11)),
                ('pago', models.IntegerField(default=0)),
            ],
        ),
    ]
