# Generated by Django 2.0.1 on 2018-02-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipoideal', '0009_auto_20180222_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='notificacionesEI',
            fields=[
                ('idnotificacion', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=20)),
                ('estado', models.CharField(default='1', max_length=1)),
                ('sala', models.CharField(default='', max_length=30)),
                ('ganador', models.CharField(default='no', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PagoSalaEI',
            fields=[
                ('idjuego', models.AutoField(primary_key=True, serialize=False)),
                ('nombreJuego', models.CharField(max_length=30)),
                ('grupo', models.CharField(max_length=30)),
                ('user', models.CharField(max_length=20)),
                ('estadopago', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pozo_salaEI',
            fields=[
                ('idjuego', models.AutoField(primary_key=True, serialize=False)),
                ('nombreJuego', models.CharField(max_length=30)),
                ('dinero', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='resultadosEI',
            fields=[
                ('idresultado', models.AutoField(primary_key=True, serialize=False)),
                ('nombreJuego', models.CharField(max_length=30)),
                ('grupo', models.CharField(max_length=30)),
                ('user', models.CharField(max_length=20)),
                ('pago', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SalaApuestasEI',
            fields=[
                ('idjuego', models.AutoField(primary_key=True, serialize=False)),
                ('nombreJuego', models.CharField(max_length=30)),
                ('grupo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='salaEI',
            fields=[
                ('idjuego', models.AutoField(primary_key=True, serialize=False)),
                ('nombreJuego', models.CharField(max_length=30)),
                ('grupo', models.CharField(max_length=30)),
                ('cantpreguntas', models.IntegerField()),
                ('estado', models.CharField(max_length=11)),
                ('pago', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='scoreEI',
            fields=[
                ('idEI', models.AutoField(primary_key=True, serialize=False)),
                ('grupo', models.CharField(max_length=30)),
                ('user', models.CharField(max_length=20)),
                ('sala', models.CharField(max_length=20)),
                ('puntaje', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ScorejuegoEI',
            fields=[
                ('idjuego', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=20)),
                ('grupo', models.CharField(max_length=30)),
                ('resultado', models.FloatField(default=0)),
                ('nombreJuego', models.CharField(max_length=30)),
            ],
        ),
    ]
