# Generated by Django 2.0.1 on 2018-02-23 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipoideal', '0010_notificacionesei_pagosalaei_pozo_salaei_resultadosei_salaapuestasei_salaei_scoreei_scorejuegoei'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaei',
            name='cantpreguntas',
        ),
    ]
